GET http://localhost:3001/getall HTTP/1.1


###

POST http://localhost:3001/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmNjYjk2OWMxZDI5NzVlNDg5MzA0MzIiLCJlbWFpbCI6ImhlbnJpcXVlNUBnbWFpbC5jb20iLCJpYXQiOjE2NTc3Mzk1NjN9.HrgQ51Y7sEV7KL1sfz4apvggqlCvx02O5GJBOOZ5hmM

{
    "name": "Oi",
    "email": "henriquem@gmail.com",
    "mobile": "eee",
    "phone": "fff",
    "password": "123456"
}

### 

PATCH http://localhost:3001/update HTTP/1.1
content-type: application/json

{
    "name": "henrique update",
    "email": "henrique6@gmail.com",
    "mobile": "12345",
    "phone": "45678",
    "password": "123456"
}

###

DELETE http://localhost:3001/delete/?email=henrique@gmail.com HTTP/1.1
content-type: application/json

###

GET http://localhost:3001/login HTTP/1.1
content-type: application/json

{
    "email": "henrique5@gmail.com",
    "password": "123456"
}